//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elevate_Mall_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop
    {
        public int Id { get; set; }
        public Nullable<int> Mall_id { get; set; }
        public Nullable<int> Categroy_id { get; set; }
        public Nullable<int> Subcategory_id { get; set; }
        public Nullable<int> Item_id { get; set; }
        public string Description { get; set; }
        public string Discounts { get; set; }
    }
}
